global.UPLOAD_ERR_OK = 0;
global.UPLOAD_ERR_INI_SIZE = 1;
global.UPLOAD_ERR_FORM_SIZE = 2;
global.UPLOAD_ERR_PARTIAL = 3;
global.UPLOAD_ERR_NO_FILE = 4;
global.UPLOAD_ERR_NO_TMP_DIR = 6;
global.UPLOAD_ERR_CANT_WRITE = 7;
global.UPLOAD_ERR_EXTENSION = 8;

module.exports = {
  UPLOAD_ERR_OK: global.UPLOAD_ERR_OK,
  UPLOAD_ERR_INI_SIZE: global.UPLOAD_ERR_INI_SIZE,
  UPLOAD_ERR_FORM_SIZE: global.UPLOAD_ERR_FORM_SIZE,
  UPLOAD_ERR_PARTIAL: global.UPLOAD_ERR_PARTIAL,
  UPLOAD_ERR_NO_FILE: global.UPLOAD_ERR_NO_FILE,
  UPLOAD_ERR_NO_TMP_DIR: global.UPLOAD_ERR_NO_TMP_DIR,
  UPLOAD_ERR_CANT_WRITE: global.UPLOAD_ERR_CANT_WRITE,
  UPLOAD_ERR_EXTENSION: global.UPLOAD_ERR_EXTENSION
};
